# Generated by Django 5.1.6 on 2025-03-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='en_name',
        ),
        migrations.AddField(
            model_name='role',
            name='fa_name',
            field=models.CharField(default='accountant', max_length=50, unique=True, verbose_name='role name'),
            preserve_default=False,
        ),
    ]
