# Generated by Django 5.1.6 on 2025-03-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_name_role_en_name_role_fa_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='role',
            name='en_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='en name'),
        ),
        migrations.AlterField(
            model_name='role',
            name='fa_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='fa name'),
        ),
    ]
