[project]
name = "medical"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.6",
    "django-jalali>=7.3.0",
    "ippanel>=2.0.7",
    "pillow>=11.1.0",
    "requests>=2.32.3",
    "xlwt>=1.3.0",
]
