# Generated by Django 5.1.6 on 2025-03-05 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('department', models.CharField(choices=[('rehabilitation', 'توانبخشی'), ('nursing', 'پرستاری'), ('medical', 'پزشکی'), ('care', 'مراقبت')], max_length=20, verbose_name='بخش')),
                ('service_performed', models.CharField(choices=[('occupational_therapy', 'کاردرمانی'), ('speech_therapy', 'گفتار درمانی'), ('physiotherapy', 'فیزیوتراپی'), ('other', 'سایر')], max_length=20, verbose_name='خدمت انحام شده')),
                ('status', models.CharField(choices=[('under_review', 'در دست بررسی'), ('provided', 'منجر به خدمت')], max_length=20, verbose_name='وضعیت')),
                ('requested_service', models.CharField(blank=True, max_length=255, null=True, verbose_name='خدمت مورد نیاز')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('service_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ارائه خدمت')),
                ('provided_service', models.CharField(blank=True, max_length=100, null=True, verbose_name='خدمت ارائه شده')),
                ('other_service', models.CharField(blank=True, max_length=255, null=True, verbose_name='سایر خدمات')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_services', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست خدمت',
                'verbose_name_plural': 'درخواست\u200cهای خدمات',
                'ordering': ['-created_at'],
            },
        ),
    ]
