# Generated by Django 5.1.6 on 2025-03-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='provided_service',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_performed',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='خدمت انجام شده'),
        ),
    ]
