# Generated by Django 5.1.6 on 2025-03-06 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_remove_servicerequest_provided_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('specialist_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی کارشناس یا پزشک')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ دریافتی کل (تومان)')),
                ('consumed_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ مصرفی (تومان)')),
                ('doctor_share', models.PositiveIntegerField(default=0, verbose_name='حق و سهم پزشک (تومان)')),
                ('consumed_type', models.CharField(blank=True, max_length=255, verbose_name='نوع مصرفی')),
                ('transaction_date', models.DateField(verbose_name='تاریخ تراکنش')),
                ('consume_share', models.PositiveIntegerField(default=0, verbose_name='حق و سهم مصرف (تومان)')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='medical.servicerequest', verbose_name='درخواست خدمت')),
            ],
            options={
                'verbose_name': 'اطلاعات مالی خدمت',
                'verbose_name_plural': 'اطلاعات مالی خدمات',
            },
        ),
    ]
