# Generated by Django 5.1.6 on 2025-03-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_servicefinancialinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefinancialinfo',
            name='transaction_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تراکنش'),
        ),
    ]
