# Generated by Django 5.1.6 on 2025-03-07 07:20

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_alter_servicefinancialinfo_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefinancialinfo',
            name='transaction_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تراکنش'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ارائه خدمت'),
        ),
    ]
