# Generated by Django 5.1.6 on 2025-03-07 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_servicefinancialinfo_transaction_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefinancialinfo',
            name='center_share',
            field=models.PositiveIntegerField(default=0, verbose_name='حق السهم مرکز (تومان)'),
        ),
        migrations.AddField(
            model_name='servicefinancialinfo',
            name='referred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_services', to=settings.AUTH_USER_MODEL, verbose_name='ارجاع شده به'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_performed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='خدمت انجام شده'),
        ),
    ]
