# Generated by Django 5.1.6 on 2025-03-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_servicefinancialinfo_center_share_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'verbose_name': 'درخواست خدمت', 'verbose_name_plural': 'درخواست\u200cهای خدمت'},
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_performed',
            field=models.CharField(blank=True, choices=[('occupational_therapy', 'کاردرمانی'), ('speech_therapy', 'گفتار درمانی'), ('physiotherapy', 'فیزیوتراپی'), ('injection', 'تزریقات'), ('wound_dressing', 'پانسمان زخم'), ('bladder_catheterization', 'سونداژ مثانه'), ('antibiotic_therapy', 'آنتی بیوتیک تراپی'), ('serum_trap', 'سرم تراپ'), ('general_visit', 'ویزیت عمومی'), ('specialist_visit', 'ویزیت تخصصی'), ('super_specialist_visit', 'ویزیت فوق تخصصی'), ('home_care', 'مراقبت در خانه'), ('hospital_care', 'مراقبت در بیمارستان'), ('other', 'سایر')], max_length=50, null=True, verbose_name='خدمت انجام شده'),
        ),
    ]
