# Generated by Django 5.1.6 on 2025-03-07 09:22

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_alter_servicerequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('item_type', models.CharField(max_length=255, verbose_name='نوع اقلام')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ دریافتی (تومان)')),
                ('request_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ')),
                ('consumption', models.CharField(blank=True, max_length=255, null=True, verbose_name='مصرف')),
                ('center_share', models.PositiveIntegerField(default=0, verbose_name='حق السهم مرکز (تومان)')),
                ('consume_share', models.PositiveIntegerField(default=0, verbose_name='حق السهم مصرف (تومان)')),
                ('referred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_equipments', to=settings.AUTH_USER_MODEL, verbose_name='ارجاع شده به')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_equipments', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست تجهیزات',
                'verbose_name_plural': 'درخواست\u200cهای تجهیزات',
            },
        ),
    ]
