# Generated by Django 5.1.6 on 2025-03-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_equipmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrequest',
            name='consume_share',
            field=models.PositiveIntegerField(default=0, verbose_name='حق السهم معرف (تومان)'),
        ),
        migrations.AlterField(
            model_name='servicefinancialinfo',
            name='consume_share',
            field=models.PositiveIntegerField(default=0, verbose_name='حق و سهم معرف (تومان)'),
        ),
    ]
