# Generated by Django 5.1.6 on 2025-03-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_alter_equipmentrequest_consume_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequest',
            name='referrer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام معرف'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='referrer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام معرف'),
        ),
    ]
