# Generated by Django 5.1.6 on 2025-03-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_equipmentrequest_referrer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrequest',
            name='center_share',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حق السهم مرکز (تومان)'),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='consume_share',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حق السهم مصرف (تومان)'),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ دریافتی (تومان)'),
        ),
        migrations.AlterField(
            model_name='servicefinancialinfo',
            name='center_share',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حق السهم مرکز (تومان)'),
        ),
        migrations.AlterField(
            model_name='servicefinancialinfo',
            name='consume_share',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حق و سهم معرف (تومان)'),
        ),
        migrations.AlterField(
            model_name='servicefinancialinfo',
            name='consumed_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ مصرفی (تومان)'),
        ),
        migrations.AlterField(
            model_name='servicefinancialinfo',
            name='doctor_share',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حق و سهم پزشک (تومان)'),
        ),
        migrations.AlterField(
            model_name='servicefinancialinfo',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ دریافتی کل (تومان)'),
        ),
    ]
