# Generated by Django 5.1.6 on 2025-03-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_alter_equipmentrequest_center_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ ارائه خدمت'),
        ),
    ]
