# Generated by Django 5.1.6 on 2025-03-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_alter_servicerequest_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefinancialinfo',
            name='referral_reason',
            field=models.TextField(blank=True, null=True, verbose_name='علت ارجاع'),
        ),
    ]
