# Generated by Django 5.1.6 on 2025-03-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_servicefinancialinfo_referral_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequest',
            name='referral_reason',
            field=models.TextField(blank=True, null=True, verbose_name='علت ارجاع'),
        ),
    ]
