# Generated by Django 5.1.6 on 2025-03-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0014_equipmentrequest_referral_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefinancialinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
