# Generated by Django 5.1.6 on 2025-03-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0015_servicefinancialinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefinancialinfo',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='تصویر رسید'),
        ),
        migrations.AlterField(
            model_name='servicefinancialinfo',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ تراکنش'),
        ),
    ]
