# Generated by Django 5.1.6 on 2025-03-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0016_servicefinancialinfo_receipt_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_receipts/', verbose_name='تصویر رسید'),
        ),
    ]
