# Generated by Django 5.1.6 on 2025-03-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0017_equipmentrequest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequest',
            name='payment_receiver',
            field=models.CharField(blank=True, choices=[('specialist', 'توسط کارشناس اعزامی'), ('center', 'توسط مرکز')], default='center', max_length=20, null=True, verbose_name='دریافت وجه از'),
        ),
        migrations.AddField(
            model_name='servicefinancialinfo',
            name='payment_receiver',
            field=models.CharField(blank=True, choices=[('specialist', 'توسط کارشناس اعزامی'), ('center', 'توسط مرکز')], default='center', max_length=50, null=True, verbose_name='دریافت وجه از'),
        ),
    ]
