# Generated by Django 5.1.6 on 2025-03-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0018_equipmentrequest_payment_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrequest',
            name='request_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ'),
        ),
    ]
