# Generated by Django 5.1.6 on 2025-05-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0019_alter_equipmentrequest_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
