# Generated by Django 5.2.4 on 2025-07-22 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بیمار')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='شماره تماس')),
                ('national_id', models.CharField(blank=True, max_length=10, verbose_name='کد ملی')),
                ('gender', models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100, verbose_name='نوع خدمت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خدمت')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
    ]
