# Generated by Django 5.2.4 on 2025-07-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('rehabilitation', 'بازتوانی'), ('medical', 'پزشکی'), ('nursing', 'پرستاری'), ('care', 'مراقبت')], max_length=50, verbose_name='نوع خدمت'),
        ),
    ]
