# Generated by Django 5.2.4 on 2025-07-22 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(verbose_name='تاریخ خدمت'),
        ),
        migrations.AlterField(
            model_name='service',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('rehabilitation', 'بازتوانی'), ('medical', 'پزشکی'), ('nursing', 'پرستاری'), ('care', 'مراقبت')], max_length=20, verbose_name='نوع خدمت'),
        ),
    ]
