# Generated by Django 5.2.4 on 2025-07-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_patient_address_patient_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='کد بیمه'),
        ),
    ]
